/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=web/wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv web/cloudflare-env.d.ts` (hash: 1973f30a6c60f8f4958bb4bbd14aeb91)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
