/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 3fbcfa2956556ebfef505afaced41a62)
interface __BaseEnv_CloudflareEnv {
	CHAT_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	TURNSTILE_HOSTNAMES: "met-collection-agent.ajaykasu7.workers.dev";
	ORIGIN_AUTH_TOKEN: string;
	TURNSTILE_SECRET: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_HOSTNAMES" | "ORIGIN_AUTH_TOKEN" | "TURNSTILE_SECRET">> {}
}
